// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo
{

    // ApiKey
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class ApiKeyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApiKey>
    {
        public ApiKeyConfiguration()
            : this("dbo")
        {
        }

        public ApiKeyConfiguration(string schema)
        {
            Property(x => x.UserAccountId).IsOptional();
            Property(x => x.UseCId).IsOptional();

        }
    }

}
// </auto-generated>
