// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // Application
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Application
    {
        public long ApplicationId { get; set; } // ApplicationId (Primary key)
        public string ApplicationKey { get; set; } // ApplicationKey (length: 50)
        public string Description { get; set; } // Description (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child ApiKeys where [ApiKey].[ApplicationId] point to this entity (FK_AKE_ApiKeys_APP_Applications)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApiKey> ApiKeys { get; set; } // ApiKey.FK_AKE_ApiKeys_APP_Applications

        public Application()
        {
            ApiKeys = new System.Collections.Generic.List<ApiKey>();
        }
    }

}
// </auto-generated>
