// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // CLI_Clients
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class CliClient
    {
        public System.Guid CliCId { get; set; } // CLI_cID (Primary key)
        public System.DateTime CliDtCreated { get; set; } // CLI_dtCreated
        public System.DateTime CliDtLastModified { get; set; } // CLI_dtLastModified
        public System.DateTime? CliDtDeleted { get; set; } // CLI_dtDeleted
        public string CliCName { get; set; } // CLI_cName (length: 80)
        public string CliCPrefix { get; set; } // CLI_cPrefix (length: 80)
        public string CliCMainUrl { get; set; } // CLI_cMainUrl (length: 100)
        public string CliCFormsUrl { get; set; } // CLI_cFormsUrl (length: 100)
        public string CliCSignalrUrl { get; set; } // CLI_cSignalrUrl (length: 100)
        public string CliCFtpUrl { get; set; } // CLI_cFtpUrl (length: 100)
        public string CliCExternMainUrl { get; set; } // CLI_cExternMainUrl (length: 100)
        public string CliCExternFormsUrl { get; set; } // CLI_cExternFormsUrl (length: 100)
        public string CliCExternSignalrUrl { get; set; } // CLI_cExternSignalrUrl (length: 100)
        public string CliCExternFtpUrl { get; set; } // CLI_cExternFtpUrl (length: 100)
        public bool CliBEnabled { get; set; } // CLI_bEnabled
        public bool? CliBSensorEnabled { get; set; } // CLI_bSensorEnabled
        public System.Guid? SerCId { get; set; } // SER_cID
        public bool CliBFormSync { get; set; } // CLI_bFormSync
        public bool CliBAzureMigrated { get; set; } // CLI_bAzureMigrated
        public bool CliBIsDev { get; set; } // CLI_bIsDev
        public bool CliBAllowPasswordMsgRecoveryNotFound { get; set; } // CLI_bAllowPasswordMsgRecoveryNotFound

        // Reverse navigation

        /// <summary>
        /// Child CseClientSensors where [CSE_ClientSensors].[CLI_cID] point to this entity (FK_CSE_ClientSensors_CLI_Clients)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CseClientSensor> CseClientSensors { get; set; } // CSE_ClientSensors.FK_CSE_ClientSensors_CLI_Clients
        /// <summary>
        /// Child DonDomainNames where [DON_DomainName].[CLI_cID] point to this entity (FK_DON_DomainName_CLI_Clients)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DonDomainName> DonDomainNames { get; set; } // DON_DomainName.FK_DON_DomainName_CLI_Clients
        /// <summary>
        /// Child FdcFormDefinitionVersionClients where [FDC_FormDefinitionVersionClients].[CLI_cID] point to this entity (FK_FDC_FormDefinitionVersionClients_CLI_Clients)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FdcFormDefinitionVersionClient> FdcFormDefinitionVersionClients { get; set; } // FDC_FormDefinitionVersionClients.FK_FDC_FormDefinitionVersionClients_CLI_Clients
        /// <summary>
        /// Child FstFormSyncTasks where [FST_FormSyncTasks].[CLI_cID] point to this entity (FK_FST_FormSyncTasks_CLI_Clients)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FstFormSyncTask> FstFormSyncTasks { get; set; } // FST_FormSyncTasks.FK_FST_FormSyncTasks_CLI_Clients
        /// <summary>
        /// Child UserAccountClients where [UserAccountClient].[CLI_cID] point to this entity (FK_UAC_UserAccountClients_CLI_Clients)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserAccountClient> UserAccountClients { get; set; } // UserAccountClient.FK_UAC_UserAccountClients_CLI_Clients
        /// <summary>
        /// Child UseUsers where [USE_Users].[CLI_cID] point to this entity (FK_USE_Users_CLI_Clients)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UseUser> UseUsers { get; set; } // USE_Users.FK_USE_Users_CLI_Clients

        // Foreign keys

        /// <summary>
        /// Parent SerServer pointed by [CLI_Clients].([SerCId]) (FK_CLI_Clients_SER_Servers)
        /// </summary>
        public virtual SerServer SerServer { get; set; } // FK_CLI_Clients_SER_Servers

        public CliClient()
        {
            CliBEnabled = true;
            CliBSensorEnabled = true;
            CliBFormSync = true;
            CliBAzureMigrated = false;
            CliBIsDev = false;
            CliBAllowPasswordMsgRecoveryNotFound = false;
            CseClientSensors = new System.Collections.Generic.List<CseClientSensor>();
            DonDomainNames = new System.Collections.Generic.List<DonDomainName>();
            FdcFormDefinitionVersionClients = new System.Collections.Generic.List<FdcFormDefinitionVersionClient>();
            FstFormSyncTasks = new System.Collections.Generic.List<FstFormSyncTask>();
            UseUsers = new System.Collections.Generic.List<UseUser>();
            UserAccountClients = new System.Collections.Generic.List<UserAccountClient>();
        }
    }

}
// </auto-generated>
