// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo
{

    // CLI_Clients
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class CliClientConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CliClient>
    {
        public CliClientConfiguration()
            : this("dbo")
        {
        }

        public CliClientConfiguration(string schema)
        {
            Property(x => x.CliDtDeleted).IsOptional();
            Property(x => x.CliCPrefix).IsUnicode(false);
            Property(x => x.CliCMainUrl).IsOptional().IsUnicode(false);
            Property(x => x.CliCFormsUrl).IsOptional().IsUnicode(false);
            Property(x => x.CliCSignalrUrl).IsOptional().IsUnicode(false);
            Property(x => x.CliCFtpUrl).IsOptional().IsUnicode(false);
            Property(x => x.CliCExternMainUrl).IsOptional().IsUnicode(false);
            Property(x => x.CliCExternFormsUrl).IsOptional().IsUnicode(false);
            Property(x => x.CliCExternSignalrUrl).IsOptional().IsUnicode(false);
            Property(x => x.CliCExternFtpUrl).IsOptional().IsUnicode(false);
            Property(x => x.CliBSensorEnabled).IsOptional();
            Property(x => x.SerCId).IsOptional();

        }
    }

}
// </auto-generated>
