// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // Company
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Company
    {
        public long CompanyId { get; set; } // CompanyId (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Phone { get; set; } // Phone (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child UserAccounts where [UserAccount].[CompanyId] point to this entity (FK_USA_UserAccounts_USC_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserAccount> UserAccounts { get; set; } // UserAccount.FK_USA_UserAccounts_USC_Company

        public Company()
        {
            UserAccounts = new System.Collections.Generic.List<UserAccount>();
        }
    }

}
// </auto-generated>
