// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // CSE_ClientSensors
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class CseClientSensor
    {
        public System.Guid CseCId { get; set; } // CSE_cID (Primary key)
        public System.DateTime CseDtCreated { get; set; } // CSE_dtCreated
        public System.DateTime CseDtLastModified { get; set; } // CSE_dtLastModified
        public System.DateTime? CseDtDeleted { get; set; } // CSE_dtDeleted
        public System.Guid? CliCId { get; set; } // CLI_cID
        public bool CseBEnabled { get; set; } // CSE_bEnabled
        public string CseCKey { get; set; } // CSE_cKey (length: 50)
        public string CseCDesc { get; set; } // CSE_cDesc (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent CliClient pointed by [CSE_ClientSensors].([CliCId]) (FK_CSE_ClientSensors_CLI_Clients)
        /// </summary>
        public virtual CliClient CliClient { get; set; } // FK_CSE_ClientSensors_CLI_Clients

        public CseClientSensor()
        {
            CseBEnabled = true;
        }
    }

}
// </auto-generated>
