// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // DON_DomainName
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class DonDomainNameConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DonDomainName>
    {
        public DonDomainNameConfiguration()
            : this("dbo")
        {
        }

        public DonDomainNameConfiguration(string schema)
        {
            ToTable("DON_DomainName", schema);
            HasKey(x => x.DonLId);

            Property(x => x.DonLId).HasColumnName(@"DON_lID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CliCId).HasColumnName(@"CLI_cID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.DonCDomainName).HasColumnName(@"DON_cDomainName").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);

            // Foreign keys
            HasRequired(a => a.CliClient).WithMany(b => b.DonDomainNames).HasForeignKey(c => c.CliCId).WillCascadeOnDelete(false); // FK_DON_DomainName_CLI_Clients
        }
    }

}
// </auto-generated>
