// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // DON_DomainName
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class DonDomainName
    {
        public int DonLId { get; set; } // DON_lID (Primary key)
        public System.Guid CliCId { get; set; } // CLI_cID
        public string DonCDomainName { get; set; } // DON_cDomainName (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent CliClient pointed by [DON_DomainName].([CliCId]) (FK_DON_DomainName_CLI_Clients)
        /// </summary>
        public virtual CliClient CliClient { get; set; } // FK_DON_DomainName_CLI_Clients
    }

}
// </auto-generated>
