// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // FDC_FormDefinitionVersionClients
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class FdcFormDefinitionVersionClientConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FdcFormDefinitionVersionClient>
    {
        public FdcFormDefinitionVersionClientConfiguration()
            : this("dbo")
        {
        }

        public FdcFormDefinitionVersionClientConfiguration(string schema)
        {
            ToTable("FDC_FormDefinitionVersionClients", schema);
            HasKey(x => x.FdcIId);

            Property(x => x.FdcIId).HasColumnName(@"FDC_iID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CliCId).HasColumnName(@"CLI_cID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.FodCId).HasColumnName(@"FOD_cID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.FdcDtDeleted).HasColumnName(@"FDC_dtDeleted").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.CliClient).WithMany(b => b.FdcFormDefinitionVersionClients).HasForeignKey(c => c.CliCId).WillCascadeOnDelete(false); // FK_FDC_FormDefinitionVersionClients_CLI_Clients
            HasRequired(a => a.FodFormDefinition).WithMany(b => b.FdcFormDefinitionVersionClients).HasForeignKey(c => c.FodCId).WillCascadeOnDelete(false); // FK_FDC_FormDefinitionVersionClients_FOD_FormDefinitions
        }
    }

}
// </auto-generated>
