// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // FDC_FormDefinitionVersionClients
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class FdcFormDefinitionVersionClient
    {
        public long FdcIId { get; set; } // FDC_iID (Primary key)
        public System.Guid CliCId { get; set; } // CLI_cID
        public System.Guid FodCId { get; set; } // FOD_cID
        public System.DateTime? FdcDtDeleted { get; set; } // FDC_dtDeleted

        // Reverse navigation

        /// <summary>
        /// Child FstFormSyncTasks where [FST_FormSyncTasks].[FDC_iID] point to this entity (FK_FST_FormSyncTasks_FDC_FormDefinitionVersionClients)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FstFormSyncTask> FstFormSyncTasks { get; set; } // FST_FormSyncTasks.FK_FST_FormSyncTasks_FDC_FormDefinitionVersionClients

        // Foreign keys

        /// <summary>
        /// Parent CliClient pointed by [FDC_FormDefinitionVersionClients].([CliCId]) (FK_FDC_FormDefinitionVersionClients_CLI_Clients)
        /// </summary>
        public virtual CliClient CliClient { get; set; } // FK_FDC_FormDefinitionVersionClients_CLI_Clients
        /// <summary>
        /// Parent FodFormDefinition pointed by [FDC_FormDefinitionVersionClients].([FodCId]) (FK_FDC_FormDefinitionVersionClients_FOD_FormDefinitions)
        /// </summary>
        public virtual FodFormDefinition FodFormDefinition { get; set; } // FK_FDC_FormDefinitionVersionClients_FOD_FormDefinitions

        public FdcFormDefinitionVersionClient()
        {
            FstFormSyncTasks = new System.Collections.Generic.List<FstFormSyncTask>();
        }
    }

}
// </auto-generated>
