// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo
{

    // FDV_FormDefinitionVersions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class FdvFormDefinitionVersionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FdvFormDefinitionVersion>
    {
        public FdvFormDefinitionVersionConfiguration()
            : this("dbo")
        {
        }

        public FdvFormDefinitionVersionConfiguration(string schema)
        {
            Property(x => x.FdvDtDeleted).IsOptional();
            Property(x => x.FdvCVersion).IsUnicode(false);
            Property(x => x.FdvDtBegin).IsOptional();
            Property(x => x.FdvCForm).IsOptional();
            Property(x => x.FdvCWebForm).IsOptional();
            Property(x => x.FdvCTextForm).IsOptional();

        }
    }

}
// </auto-generated>
