// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // FDV_FormDefinitionVersions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class FdvFormDefinitionVersion
    {
        public System.Guid FdvCId { get; set; } // FDV_cID (Primary key)
        public System.Guid FodCId { get; set; } // FOD_cID
        public System.DateTime FdvDtCreated { get; set; } // FDV_dtCreated
        public System.DateTime FdvDtLastModified { get; set; } // FDV_dtLastModified
        public System.DateTime? FdvDtDeleted { get; set; } // FDV_dtDeleted
        public string FdvCVersion { get; set; } // FDV_cVersion (length: 20)
        public System.DateTime? FdvDtBegin { get; set; } // FDV_dtBegin
        public string FdvCForm { get; set; } // FDV_cForm
        public string FdvCWebForm { get; set; } // FDV_cWebForm
        public string FdvCTextForm { get; set; } // FDV_cTextForm

        // Reverse navigation

        /// <summary>
        /// Child FstFormSyncTasks where [FST_FormSyncTasks].[FDV_cID] point to this entity (FK_FST_FormSyncTasks_FDV_FormDefinitionVersions)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FstFormSyncTask> FstFormSyncTasks { get; set; } // FST_FormSyncTasks.FK_FST_FormSyncTasks_FDV_FormDefinitionVersions
        /// <summary>
        /// Child HfdHistoryFormDefinitionVersions where [HFD_HistoryFormDefinitionVersions].[FDV_cId] point to this entity (FK_HFD_HistoryFormDefinitionVersions_FDV_FormDefinitionVersions)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<HfdHistoryFormDefinitionVersion> HfdHistoryFormDefinitionVersions { get; set; } // HFD_HistoryFormDefinitionVersions.FK_HFD_HistoryFormDefinitionVersions_FDV_FormDefinitionVersions

        // Foreign keys

        /// <summary>
        /// Parent FodFormDefinition pointed by [FDV_FormDefinitionVersions].([FodCId]) (FK_FDV_FormDefinitionVersions_FOD_FormDefinitions)
        /// </summary>
        public virtual FodFormDefinition FodFormDefinition { get; set; } // FK_FDV_FormDefinitionVersions_FOD_FormDefinitions

        public FdvFormDefinitionVersion()
        {
            FstFormSyncTasks = new System.Collections.Generic.List<FstFormSyncTask>();
            HfdHistoryFormDefinitionVersions = new System.Collections.Generic.List<HfdHistoryFormDefinitionVersion>();
        }
    }

}
// </auto-generated>
