// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // FDV_FormDefinitionVersions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class FdvFormDefinitionVersionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FdvFormDefinitionVersion>
    {
        public FdvFormDefinitionVersionConfiguration()
            : this("dbo")
        {
        }

        public FdvFormDefinitionVersionConfiguration(string schema)
        {
            ToTable("FDV_FormDefinitionVersions", schema);
            HasKey(x => x.FdvCId);

            Property(x => x.FdvCId).HasColumnName(@"FDV_cID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.FodCId).HasColumnName(@"FOD_cID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.FdvDtCreated).HasColumnName(@"FDV_dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.FdvDtLastModified).HasColumnName(@"FDV_dtLastModified").HasColumnType("datetime").IsRequired();
            Property(x => x.FdvDtDeleted).HasColumnName(@"FDV_dtDeleted").HasColumnType("datetime").IsOptional();
            Property(x => x.FdvCVersion).HasColumnName(@"FDV_cVersion").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.FdvDtBegin).HasColumnName(@"FDV_dtBegin").HasColumnType("datetime").IsOptional();
            Property(x => x.FdvCForm).HasColumnName(@"FDV_cForm").HasColumnType("xml").IsOptional();
            Property(x => x.FdvCWebForm).HasColumnName(@"FDV_cWebForm").HasColumnType("xml").IsOptional();
            Property(x => x.FdvCTextForm).HasColumnName(@"FDV_cTextForm").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasRequired(a => a.FodFormDefinition).WithMany(b => b.FdvFormDefinitionVersions).HasForeignKey(c => c.FodCId).WillCascadeOnDelete(false); // FK_FDV_FormDefinitionVersions_FOD_FormDefinitions
        }
    }

}
// </auto-generated>
