// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo
{

    // FST_FormSyncTasks
    [Table("FST_FormSyncTasks", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class FstFormSyncTask
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"FST_iID", Order = 1, TypeName = "bigint")]
        [Index(@"PK_FST_FormSyncTasks", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Fst i ID")]
        public long FstIId { get; set; } // FST_iID (Primary key)

        [Column(@"FST_dtCreated", Order = 2, TypeName = "datetime")]
        [Required]
        [Display(Name = "Fst dt created")]
        public System.DateTime FstDtCreated { get; set; } // FST_dtCreated

        [Column(@"FST_cAction", Order = 3, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Fst c action")]
        public string FstCAction { get; set; } // FST_cAction (length: 50)

        [Column(@"CLI_cID", Order = 4, TypeName = "uniqueidentifier")]
        [Display(Name = "Cli c ID")]
        public System.Guid? CliCId { get; set; } // CLI_cID

        [Column(@"FOD_cID", Order = 5, TypeName = "uniqueidentifier")]
        [Display(Name = "Fod c ID")]
        public System.Guid? FodCId { get; set; } // FOD_cID

        [Column(@"FDV_cID", Order = 6, TypeName = "uniqueidentifier")]
        [Display(Name = "Fdv c ID")]
        public System.Guid? FdvCId { get; set; } // FDV_cID

        [Column(@"FDC_iID", Order = 7, TypeName = "bigint")]
        [Display(Name = "Fdc i ID")]
        public long? FdcIId { get; set; } // FDC_iID

        [Column(@"FST_cError", Order = 8, TypeName = "varchar(max)")]
        [Display(Name = "Fst c error")]
        public string FstCError { get; set; } // FST_cError

        // Foreign keys

        /// <summary>
        /// Parent CliClient pointed by [FST_FormSyncTasks].([CliCId]) (FK_FST_FormSyncTasks_CLI_Clients)
        /// </summary>
        [ForeignKey("CliCId")] public virtual CliClient CliClient { get; set; } // FK_FST_FormSyncTasks_CLI_Clients
        /// <summary>
        /// Parent FdcFormDefinitionVersionClient pointed by [FST_FormSyncTasks].([FdcIId]) (FK_FST_FormSyncTasks_FDC_FormDefinitionVersionClients)
        /// </summary>
        [ForeignKey("FdcIId")] public virtual FdcFormDefinitionVersionClient FdcFormDefinitionVersionClient { get; set; } // FK_FST_FormSyncTasks_FDC_FormDefinitionVersionClients
        /// <summary>
        /// Parent FdvFormDefinitionVersion pointed by [FST_FormSyncTasks].([FdvCId]) (FK_FST_FormSyncTasks_FDV_FormDefinitionVersions)
        /// </summary>
        [ForeignKey("FdvCId")] public virtual FdvFormDefinitionVersion FdvFormDefinitionVersion { get; set; } // FK_FST_FormSyncTasks_FDV_FormDefinitionVersions
        /// <summary>
        /// Parent FodFormDefinition pointed by [FST_FormSyncTasks].([FodCId]) (FK_FST_FormSyncTasks_FOD_FormDefinitions)
        /// </summary>
        [ForeignKey("FodCId")] public virtual FodFormDefinition FodFormDefinition { get; set; } // FK_FST_FormSyncTasks_FOD_FormDefinitions
    }

}
// </auto-generated>
