// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // FST_FormSyncTasks
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class FstFormSyncTask
    {
        public long FstIId { get; set; } // FST_iID (Primary key)
        public System.DateTime FstDtCreated { get; set; } // FST_dtCreated
        public string FstCAction { get; set; } // FST_cAction (length: 50)
        public System.Guid? CliCId { get; set; } // CLI_cID
        public System.Guid? FodCId { get; set; } // FOD_cID
        public System.Guid? FdvCId { get; set; } // FDV_cID
        public long? FdcIId { get; set; } // FDC_iID
        public string FstCError { get; set; } // FST_cError

        // Foreign keys

        /// <summary>
        /// Parent CliClient pointed by [FST_FormSyncTasks].([CliCId]) (FK_FST_FormSyncTasks_CLI_Clients)
        /// </summary>
        public virtual CliClient CliClient { get; set; } // FK_FST_FormSyncTasks_CLI_Clients
        /// <summary>
        /// Parent FdcFormDefinitionVersionClient pointed by [FST_FormSyncTasks].([FdcIId]) (FK_FST_FormSyncTasks_FDC_FormDefinitionVersionClients)
        /// </summary>
        public virtual FdcFormDefinitionVersionClient FdcFormDefinitionVersionClient { get; set; } // FK_FST_FormSyncTasks_FDC_FormDefinitionVersionClients
        /// <summary>
        /// Parent FdvFormDefinitionVersion pointed by [FST_FormSyncTasks].([FdvCId]) (FK_FST_FormSyncTasks_FDV_FormDefinitionVersions)
        /// </summary>
        public virtual FdvFormDefinitionVersion FdvFormDefinitionVersion { get; set; } // FK_FST_FormSyncTasks_FDV_FormDefinitionVersions
        /// <summary>
        /// Parent FodFormDefinition pointed by [FST_FormSyncTasks].([FodCId]) (FK_FST_FormSyncTasks_FOD_FormDefinitions)
        /// </summary>
        public virtual FodFormDefinition FodFormDefinition { get; set; } // FK_FST_FormSyncTasks_FOD_FormDefinitions
    }

}
// </auto-generated>
