// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // HFD_HistoryFormDefinitionVersions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class HfdHistoryFormDefinitionVersion
    {
        public int HfdINoSeq { get; set; } // HFD_iNoSeq (Primary key)
        public System.Guid FdvCId { get; set; } // FDV_cId
        public System.DateTime HfdDtCreated { get; set; } // HFD_dtCreated
        public string HfdCForm { get; set; } // HFD_cForm

        // Foreign keys

        /// <summary>
        /// Parent FdvFormDefinitionVersion pointed by [HFD_HistoryFormDefinitionVersions].([FdvCId]) (FK_HFD_HistoryFormDefinitionVersions_FDV_FormDefinitionVersions)
        /// </summary>
        public virtual FdvFormDefinitionVersion FdvFormDefinitionVersion { get; set; } // FK_HFD_HistoryFormDefinitionVersions_FDV_FormDefinitionVersions
    }

}
// </auto-generated>
