// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // HFD_HistoryFormDefinitionVersions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class HfdHistoryFormDefinitionVersionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HfdHistoryFormDefinitionVersion>
    {
        public HfdHistoryFormDefinitionVersionConfiguration()
            : this("dbo")
        {
        }

        public HfdHistoryFormDefinitionVersionConfiguration(string schema)
        {
            ToTable("HFD_HistoryFormDefinitionVersions", schema);
            HasKey(x => x.HfdINoSeq);

            Property(x => x.HfdINoSeq).HasColumnName(@"HFD_iNoSeq").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FdvCId).HasColumnName(@"FDV_cId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.HfdDtCreated).HasColumnName(@"HFD_dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.HfdCForm).HasColumnName(@"HFD_cForm").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasRequired(a => a.FdvFormDefinitionVersion).WithMany(b => b.HfdHistoryFormDefinitionVersions).HasForeignKey(c => c.FdvCId).WillCascadeOnDelete(false); // FK_HFD_HistoryFormDefinitionVersions_FDV_FormDefinitionVersions
        }
    }

}
// </auto-generated>
