// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // IPS_IpServers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class IpsIpServer
    {
        public int IpsIId { get; set; } // IPS_iID (Primary key)
        public string IpsCTag { get; set; } // IPS_cTag (length: 50)
        public string IpsCWebService { get; set; } // IPS_cWebService (length: 1024)
        public string IpsCSignalRService { get; set; } // IPS_cSignalRService (length: 1024)
        public string IpsCFtpService { get; set; } // IPS_cFtpService (length: 1024)
        public string IpsCSqlIpAddress { get; set; } // IPS_cSqlIpAddress (length: 1024)
        public string IpsCBasicSqlAuthentification { get; set; } // IPS_cBasicSQLAuthentification (length: 1024)
        public string IpsCConnectionString { get; set; } // IPS_cConnectionString (length: 1024)
        public string IpsCEntitiesConnectionString { get; set; } // IPS_cEntitiesConnectionString (length: 1024)
        public string IpsCNewDatabaseSource { get; set; } // IPS_cNewDatabaseSource
        public bool IpsBEnabled { get; set; } // IPS_bEnabled

        public IpsIpServer()
        {
            IpsBEnabled = true;
        }
    }

}
// </auto-generated>
