// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // IPS_IpServers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class IpsIpServerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<IpsIpServer>
    {
        public IpsIpServerConfiguration()
            : this("dbo")
        {
        }

        public IpsIpServerConfiguration(string schema)
        {
            ToTable("IPS_IpServers", schema);
            HasKey(x => x.IpsIId);

            Property(x => x.IpsIId).HasColumnName(@"IPS_iID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IpsCTag).HasColumnName(@"IPS_cTag").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.IpsCWebService).HasColumnName(@"IPS_cWebService").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.IpsCSignalRService).HasColumnName(@"IPS_cSignalRService").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.IpsCFtpService).HasColumnName(@"IPS_cFtpService").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.IpsCSqlIpAddress).HasColumnName(@"IPS_cSqlIpAddress").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.IpsCBasicSqlAuthentification).HasColumnName(@"IPS_cBasicSQLAuthentification").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.IpsCConnectionString).HasColumnName(@"IPS_cConnectionString").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.IpsCEntitiesConnectionString).HasColumnName(@"IPS_cEntitiesConnectionString").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.IpsCNewDatabaseSource).HasColumnName(@"IPS_cNewDatabaseSource").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.IpsBEnabled).HasColumnName(@"IPS_bEnabled").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
