// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // KitTemplateAttribute
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplateAttribute
    {
        public int KitTemplateAttributeId { get; set; } // KitTemplateAttributeId (Primary key)
        public int KitTemplateId { get; set; } // KitTemplateId
        public string Name { get; set; } // Name (length: 200)
        public string Identifier { get; set; } // Identifier (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent KitTemplate pointed by [KitTemplateAttribute].([KitTemplateId]) (FK_KitTemplateAttribute_KitTemplate)
        /// </summary>
        public virtual KitTemplate KitTemplate { get; set; } // FK_KitTemplateAttribute_KitTemplate
    }

}
// </auto-generated>
