// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // KitTemplateMeasureDefinition
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplateMeasureDefinition
    {
        public int KitTemplateMeasureDefinitionId { get; set; } // KitTemplateMeasureDefinitionId (Primary key)
        public int? KitTemplateId { get; set; } // KitTemplateId
        public string Name { get; set; } // Name (length: 80)
        public string Unit { get; set; } // Unit (length: 30)
        public string MeasureType { get; set; } // MeasureType (length: 5)
        public string Formula { get; set; } // Formula (length: 512)
        public string FormatString { get; set; } // FormatString (length: 30)
        public string UnitFormat { get; set; } // UnitFormat (length: 200)
        public string Form { get; set; } // Form
        public System.Guid? FodCId { get; set; } // FOD_cID

        // Foreign keys

        /// <summary>
        /// Parent FodFormDefinition pointed by [KitTemplateMeasureDefinition].([FodCId]) (FK_KitTemplateMeasureDefinition_FOD_FormDefinitions)
        /// </summary>
        public virtual FodFormDefinition FodFormDefinition { get; set; } // FK_KitTemplateMeasureDefinition_FOD_FormDefinitions
        /// <summary>
        /// Parent KitTemplate pointed by [KitTemplateMeasureDefinition].([KitTemplateId]) (FK_KitTemplateMeasureDefinition_KitTemplate)
        /// </summary>
        public virtual KitTemplate KitTemplate { get; set; } // FK_KitTemplateMeasureDefinition_KitTemplate
    }

}
// </auto-generated>
