// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // KitTemplate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplate
    {
        public int KitTemplateId { get; set; } // KitTemplateId (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Abbr { get; set; } // Abbr (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child KitTemplateAttributes where [KitTemplateAttribute].[KitTemplateId] point to this entity (FK_KitTemplateAttribute_KitTemplate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<KitTemplateAttribute> KitTemplateAttributes { get; set; } // KitTemplateAttribute.FK_KitTemplateAttribute_KitTemplate
        /// <summary>
        /// Child KitTemplateMeasureDefinitions where [KitTemplateMeasureDefinition].[KitTemplateId] point to this entity (FK_KitTemplateMeasureDefinition_KitTemplate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<KitTemplateMeasureDefinition> KitTemplateMeasureDefinitions { get; set; } // KitTemplateMeasureDefinition.FK_KitTemplateMeasureDefinition_KitTemplate

        public KitTemplate()
        {
            KitTemplateAttributes = new System.Collections.Generic.List<KitTemplateAttribute>();
            KitTemplateMeasureDefinitions = new System.Collections.Generic.List<KitTemplateMeasureDefinition>();
        }
    }

}
// </auto-generated>
