// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo
{

    // KitTemplateMeasureDefinition
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplateMeasureDefinitionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<KitTemplateMeasureDefinition>
    {
        public KitTemplateMeasureDefinitionConfiguration()
            : this("dbo")
        {
        }

        public KitTemplateMeasureDefinitionConfiguration(string schema)
        {
            Property(x => x.KitTemplateId).IsOptional();
            Property(x => x.Unit).IsOptional();
            Property(x => x.MeasureType).IsUnicode(false);
            Property(x => x.Formula).IsOptional();
            Property(x => x.FormatString).IsOptional();
            Property(x => x.UnitFormat).IsOptional();
            Property(x => x.Form).IsOptional();
            Property(x => x.FodCId).IsOptional();

        }
    }

}
// </auto-generated>
