// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // KitTemplateAttribute
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplateAttributeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<KitTemplateAttribute>
    {
        public KitTemplateAttributeConfiguration()
            : this("dbo")
        {
        }

        public KitTemplateAttributeConfiguration(string schema)
        {
            ToTable("KitTemplateAttribute", schema);
            HasKey(x => x.KitTemplateAttributeId);

            Property(x => x.KitTemplateAttributeId).HasColumnName(@"KitTemplateAttributeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.KitTemplateId).HasColumnName(@"KitTemplateId").HasColumnType("int").IsRequired();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.Identifier).HasColumnName(@"Identifier").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);

            // Foreign keys
            HasRequired(a => a.KitTemplate).WithMany(b => b.KitTemplateAttributes).HasForeignKey(c => c.KitTemplateId).WillCascadeOnDelete(false); // FK_KitTemplateAttribute_KitTemplate
        }
    }

}
// </auto-generated>
