// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // KitTemplate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplateConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<KitTemplate>
    {
        public KitTemplateConfiguration()
            : this("dbo")
        {
        }

        public KitTemplateConfiguration(string schema)
        {
            ToTable("KitTemplate", schema);
            HasKey(x => x.KitTemplateId);

            Property(x => x.KitTemplateId).HasColumnName(@"KitTemplateId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Abbr).HasColumnName(@"Abbr").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
        }
    }

}
// </auto-generated>
