// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // The table 'LastCreatedUsers' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // LastCreatedUsers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class LastCreatedUser
    {
        public System.DateTime? Dd { get; set; } // dd
        public int? TheCount { get; set; } // TheCount
        public string Clients { get; set; } // Clients
    }

}
// </auto-generated>
