// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // LOE_LogExceptions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class LoeLogException
    {
        public int LoeINoSeq { get; set; } // LOE_iNoSeq (Primary key)
        public System.Guid? CliCId { get; set; } // CLI_cID
        public System.DateTime LoeDtCreated { get; set; } // LOE_dtCreated
        public string LoeCType { get; set; } // LOE_cType (length: 50)
        public string LoeCMessage { get; set; } // LOE_cMessage
        public string LoeCNote { get; set; } // LOE_cNote
        public System.DateTime? LoeDtLastModified { get; set; } // LOE_dtLastModified
        public bool LoeBDeleted { get; set; } // LOE_bDeleted
    }

}
// </auto-generated>
