// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // LOE_LogExceptions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class LoeLogExceptionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LoeLogException>
    {
        public LoeLogExceptionConfiguration()
            : this("dbo")
        {
        }

        public LoeLogExceptionConfiguration(string schema)
        {
            ToTable("LOE_LogExceptions", schema);
            HasKey(x => x.LoeINoSeq);

            Property(x => x.LoeINoSeq).HasColumnName(@"LOE_iNoSeq").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CliCId).HasColumnName(@"CLI_cID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.LoeDtCreated).HasColumnName(@"LOE_dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.LoeCType).HasColumnName(@"LOE_cType").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.LoeCMessage).HasColumnName(@"LOE_cMessage").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.LoeCNote).HasColumnName(@"LOE_cNote").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.LoeDtLastModified).HasColumnName(@"LOE_dtLastModified").HasColumnType("datetime").IsOptional();
            Property(x => x.LoeBDeleted).HasColumnName(@"LOE_bDeleted").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
