// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo
{

    // LOE_LogExceptions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class LoeLogExceptionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LoeLogException>
    {
        public LoeLogExceptionConfiguration()
            : this("dbo")
        {
        }

        public LoeLogExceptionConfiguration(string schema)
        {
            Property(x => x.CliCId).IsOptional();
            Property(x => x.LoeCType).IsOptional().IsUnicode(false);
            Property(x => x.LoeCMessage).IsUnicode(false);
            Property(x => x.LoeCNote).IsOptional().IsUnicode(false);
            Property(x => x.LoeDtLastModified).IsOptional();
        }
    }

}
// </auto-generated>
