// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // PRE_Preferences
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class PrePreferenceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PrePreference>
    {
        public PrePreferenceConfiguration()
            : this("dbo")
        {
        }

        public PrePreferenceConfiguration(string schema)
        {
            ToTable("PRE_Preferences", schema);
            HasKey(x => x.PreIId);

            Property(x => x.PreIId).HasColumnName(@"PRE_iID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PreCKey).HasColumnName(@"PRE_cKey").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.PreCValue).HasColumnName(@"PRE_cValue").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
        }
    }

}
// </auto-generated>
