// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo
{

    // PRE_Preferences
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class PrePreferenceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PrePreference>
    {
        public PrePreferenceConfiguration()
            : this("dbo")
        {
        }

        public PrePreferenceConfiguration(string schema)
        {
            Property(x => x.PreCKey).IsOptional();
            Property(x => x.PreCValue).IsOptional();
        }
    }

}
// </auto-generated>
