// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // RightAction
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class RightAction
    {
        public long RightActionId { get; set; } // RightActionId (Primary key)
        public string ActionKey { get; set; } // ActionKey (length: 50)
        public string Description { get; set; } // Description (length: 100)
        public bool DefaultGranted { get; set; } // DefaultGranted

        // Reverse navigation

        /// <summary>
        /// Child Rights where [Right].[RightActionId] point to this entity (FK_Right_RightAction)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Right> Rights { get; set; } // Right.FK_Right_RightAction

        public RightAction()
        {
            Rights = new System.Collections.Generic.List<Right>();
        }
    }

}
// </auto-generated>
