// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // Right
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Right
    {
        public long RightId { get; set; } // RightId (Primary key)
        public long RightActionId { get; set; } // RightActionId
        public long? UserAccountGroupId { get; set; } // UserAccountGroupId
        public bool? DatabaseOwnerOnly { get; set; } // DatabaseOwnerOnly
        public bool CanCreate { get; set; } // CanCreate
        public bool CanRead { get; set; } // CanRead
        public bool CanUpdate { get; set; } // CanUpdate
        public bool CanDelete { get; set; } // CanDelete

        // Foreign keys

        /// <summary>
        /// Parent RightAction pointed by [Right].([RightActionId]) (FK_Right_RightAction)
        /// </summary>
        public virtual RightAction RightAction { get; set; } // FK_Right_RightAction
        /// <summary>
        /// Parent UserAccountGroup pointed by [Right].([UserAccountGroupId]) (FK_RIG_Rights_UAG_UserAccountGroups)
        /// </summary>
        public virtual UserAccountGroup UserAccountGroup { get; set; } // FK_RIG_Rights_UAG_UserAccountGroups

        public Right()
        {
            DatabaseOwnerOnly = false;
            CanCreate = false;
            CanRead = false;
            CanUpdate = false;
            CanDelete = false;
        }
    }

}
// </auto-generated>
