// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // RightAction
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class RightActionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RightAction>
    {
        public RightActionConfiguration()
            : this("dbo")
        {
        }

        public RightActionConfiguration(string schema)
        {
            ToTable("RightAction", schema);
            HasKey(x => x.RightActionId);

            Property(x => x.RightActionId).HasColumnName(@"RightActionId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ActionKey).HasColumnName(@"ActionKey").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.DefaultGranted).HasColumnName(@"DefaultGranted").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
