// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // SER_Servers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class SerServer
    {
        public System.Guid SerCId { get; set; } // SER_cID (Primary key)
        public System.DateTime SerDtCreated { get; set; } // SER_dtCreated
        public System.DateTime SerDtLastModified { get; set; } // SER_dtLastModified
        public System.DateTime? SerDtDeleted { get; set; } // SER_dtDeleted
        public string SerVcName { get; set; } // SER_vcName (length: 50)
        public string SerVcJobAgentTag { get; set; } // SER_vcJobAgentTag (length: 50)
        public string SerVcConnectionStringEntities { get; set; } // SER_vcConnectionStringEntities
        public string SerVcConnectionString { get; set; } // SER_vcConnectionString
        public bool SerBEnabled { get; set; } // SER_bEnabled
        public bool SerBCreateClientAvailable { get; set; } // SER_bCreateClientAvailable

        // Reverse navigation

        /// <summary>
        /// Child CliClients where [CLI_Clients].[SER_cID] point to this entity (FK_CLI_Clients_SER_Servers)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CliClient> CliClients { get; set; } // CLI_Clients.FK_CLI_Clients_SER_Servers

        public SerServer()
        {
            SerBCreateClientAvailable = true;
            CliClients = new System.Collections.Generic.List<CliClient>();
        }
    }

}
// </auto-generated>
