// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // UNO_UserNotices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class UnoUserNoticeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UnoUserNotice>
    {
        public UnoUserNoticeConfiguration()
            : this("dbo")
        {
        }

        public UnoUserNoticeConfiguration(string schema)
        {
            ToTable("UNO_UserNotices", schema);
            HasKey(x => x.UnoCId);

            Property(x => x.UnoCId).HasColumnName(@"UNO_cID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UnoDtCreated).HasColumnName(@"UNO_dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.UnoDtLastModified).HasColumnName(@"UNO_dtLastModified").HasColumnType("datetime").IsRequired();
            Property(x => x.UnoDtDeleted).HasColumnName(@"UNO_dtDeleted").HasColumnType("datetime").IsOptional();
            Property(x => x.UnoVcConfidentialityEn).HasColumnName(@"UNO_vcConfidentialityEN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.UnoVcConfidentialityFr).HasColumnName(@"UNO_vcConfidentialityFR").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.UnoIVersion).HasColumnName(@"UNO_iVersion").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UnoVcConfidentialityEs).HasColumnName(@"UNO_vcConfidentialityES").HasColumnType("nvarchar(max)").IsOptional();
        }
    }

}
// </auto-generated>
