// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // UNO_UserNotices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class UnoUserNotice
    {
        public System.Guid UnoCId { get; set; } // UNO_cID (Primary key)
        public System.DateTime UnoDtCreated { get; set; } // UNO_dtCreated
        public System.DateTime UnoDtLastModified { get; set; } // UNO_dtLastModified
        public System.DateTime? UnoDtDeleted { get; set; } // UNO_dtDeleted
        public string UnoVcConfidentialityEn { get; set; } // UNO_vcConfidentialityEN
        public string UnoVcConfidentialityFr { get; set; } // UNO_vcConfidentialityFR
        public int UnoIVersion { get; set; } // UNO_iVersion
        public string UnoVcConfidentialityEs { get; set; } // UNO_vcConfidentialityES

        // Reverse navigation

        /// <summary>
        /// Child UseUsers where [USE_Users].[UNO_cID] point to this entity (FK_USE_Users_UNO_UserNotices)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UseUser> UseUsers { get; set; } // USE_Users.FK_USE_Users_UNO_UserNotices

        public UnoUserNotice()
        {
            UseUsers = new System.Collections.Generic.List<UseUser>();
        }
    }

}
// </auto-generated>
