// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // UserAccountClient
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class UserAccountClient
    {
        public long UserAccountClientId { get; set; } // UserAccountClientId (Primary key)
        public long UserAccountId { get; set; } // UserAccountId
        public System.Guid CliCId { get; set; } // CLI_cID
        public bool DatabaseOwner { get; set; } // DatabaseOwner

        // Foreign keys

        /// <summary>
        /// Parent CliClient pointed by [UserAccountClient].([CliCId]) (FK_UAC_UserAccountClients_CLI_Clients)
        /// </summary>
        public virtual CliClient CliClient { get; set; } // FK_UAC_UserAccountClients_CLI_Clients
        /// <summary>
        /// Parent UserAccount pointed by [UserAccountClient].([UserAccountId]) (FK_UAC_UserAccountClients_USA_UserAccounts)
        /// </summary>
        public virtual UserAccount UserAccount { get; set; } // FK_UAC_UserAccountClients_USA_UserAccounts

        public UserAccountClient()
        {
            DatabaseOwner = false;
        }
    }

}
// </auto-generated>
