// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // UserAccountClient
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class UserAccountClientConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserAccountClient>
    {
        public UserAccountClientConfiguration()
            : this("dbo")
        {
        }

        public UserAccountClientConfiguration(string schema)
        {
            ToTable("UserAccountClient", schema);
            HasKey(x => x.UserAccountClientId);

            Property(x => x.UserAccountClientId).HasColumnName(@"UserAccountClientId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserAccountId).HasColumnName(@"UserAccountId").HasColumnType("bigint").IsRequired();
            Property(x => x.CliCId).HasColumnName(@"CLI_cID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.DatabaseOwner).HasColumnName(@"DatabaseOwner").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.CliClient).WithMany(b => b.UserAccountClients).HasForeignKey(c => c.CliCId).WillCascadeOnDelete(false); // FK_UAC_UserAccountClients_CLI_Clients
            HasRequired(a => a.UserAccount).WithMany(b => b.UserAccountClients).HasForeignKey(c => c.UserAccountId).WillCascadeOnDelete(false); // FK_UAC_UserAccountClients_USA_UserAccounts
        }
    }

}
// </auto-generated>
