// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // USE_Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class UseUserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UseUser>
    {
        public UseUserConfiguration()
            : this("dbo")
        {
        }

        public UseUserConfiguration(string schema)
        {
            ToTable("USE_Users", schema);
            HasKey(x => x.UseCId);

            Property(x => x.UseIId).HasColumnName(@"USE_iID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UseCId).HasColumnName(@"USE_cID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UseDtCreated).HasColumnName(@"USE_dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.UseDtLastModified).HasColumnName(@"USE_dtLastModified").HasColumnType("datetime").IsRequired();
            Property(x => x.UseDtDeleted).HasColumnName(@"USE_dtDeleted").HasColumnType("datetime").IsOptional();
            Property(x => x.CliCId).HasColumnName(@"CLI_cID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.UseCEmail).HasColumnName(@"USE_cEmail").HasColumnType("nvarchar").IsRequired().HasMaxLength(80);
            Property(x => x.UseBExtern).HasColumnName(@"USE_bExtern").HasColumnType("bit").IsRequired();
            Property(x => x.UseBEnabled).HasColumnName(@"USE_bEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.UnoCId).HasColumnName(@"UNO_cID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.UseBIsDev).HasColumnName(@"USE_bIsDev").HasColumnType("bit").IsRequired();
            Property(x => x.UseCRestApiKey).HasColumnName(@"USE_cRestApiKey").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.MusIId).HasColumnName(@"MUS_iID").HasColumnType("bigint").IsOptional();

            // Foreign keys
            HasOptional(a => a.UnoUserNotice).WithMany(b => b.UseUsers).HasForeignKey(c => c.UnoCId).WillCascadeOnDelete(false); // FK_USE_Users_UNO_UserNotices
            HasRequired(a => a.CliClient).WithMany(b => b.UseUsers).HasForeignKey(c => c.CliCId).WillCascadeOnDelete(false); // FK_USE_Users_CLI_Clients
        }
    }

}
// </auto-generated>
