// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // USE_Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class UseUser
    {
        public int UseIId { get; set; } // USE_iID
        public System.Guid UseCId { get; set; } // USE_cID (Primary key)
        public System.DateTime UseDtCreated { get; set; } // USE_dtCreated
        public System.DateTime UseDtLastModified { get; set; } // USE_dtLastModified
        public System.DateTime? UseDtDeleted { get; set; } // USE_dtDeleted
        public System.Guid CliCId { get; set; } // CLI_cID
        public string UseCEmail { get; set; } // USE_cEmail (length: 80)
        public bool UseBExtern { get; set; } // USE_bExtern
        public bool UseBEnabled { get; set; } // USE_bEnabled
        public System.Guid? UnoCId { get; set; } // UNO_cID
        public bool UseBIsDev { get; set; } // USE_bIsDev
        public string UseCRestApiKey { get; set; } // USE_cRestApiKey (length: 50)
        public long? MusIId { get; set; } // MUS_iID

        // Reverse navigation

        /// <summary>
        /// Child ApiKeys where [ApiKey].[USE_cID] point to this entity (FK_ApiKey_USE_Users)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApiKey> ApiKeys { get; set; } // ApiKey.FK_ApiKey_USE_Users

        // Foreign keys

        /// <summary>
        /// Parent CliClient pointed by [USE_Users].([CliCId]) (FK_USE_Users_CLI_Clients)
        /// </summary>
        public virtual CliClient CliClient { get; set; } // FK_USE_Users_CLI_Clients
        /// <summary>
        /// Parent UnoUserNotice pointed by [USE_Users].([UnoCId]) (FK_USE_Users_UNO_UserNotices)
        /// </summary>
        public virtual UnoUserNotice UnoUserNotice { get; set; } // FK_USE_Users_UNO_UserNotices

        public UseUser()
        {
            UseBExtern = false;
            UseBEnabled = true;
            UseBIsDev = false;
            ApiKeys = new System.Collections.Generic.List<ApiKey>();
        }
    }

}
// </auto-generated>
