// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo
{

    // USE_Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class UseUserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UseUser>
    {
        public UseUserConfiguration()
            : this("dbo")
        {
        }

        public UseUserConfiguration(string schema)
        {
            Property(x => x.UseDtDeleted).IsOptional();
            Property(x => x.UnoCId).IsOptional();
            Property(x => x.UseCRestApiKey).IsOptional();
            Property(x => x.MusIId).IsOptional();

        }
    }

}
// </auto-generated>
