// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // VER_Versions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class VerVersionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<VerVersion>
    {
        public VerVersionConfiguration()
            : this("dbo")
        {
        }

        public VerVersionConfiguration(string schema)
        {
            ToTable("VER_Versions", schema);
            HasKey(x => x.VerCId);

            Property(x => x.VerCId).HasColumnName(@"VER_cID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.VerCKey).HasColumnName(@"VER_cKey").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.VerCValue).HasColumnName(@"VER_cValue").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.VerCAppStoreSite).HasColumnName(@"VER_cAppStoreSite").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
        }
    }

}
// </auto-generated>
