// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo
{

    // VER_Versions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class VerVersion
    {
        public System.Guid VerCId { get; set; } // VER_cID (Primary key)
        public string VerCKey { get; set; } // VER_cKey (length: 50)
        public string VerCValue { get; set; } // VER_cValue (length: 50)
        public string VerCAppStoreSite { get; set; } // VER_cAppStoreSite (length: 100)
    }

}
// </auto-generated>
