// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo.Entities
{

    // KitTemplateAttribute
    [Table("KitTemplateAttribute", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplateAttribute
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"KitTemplateAttributeId", Order = 1, TypeName = "int")]
        [Index(@"PK_KitTemplateAttribute", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Kit template attribute ID")]
        public int KitTemplateAttributeId { get; set; } // KitTemplateAttributeId (Primary key)

        [Column(@"KitTemplateId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Kit template ID")]
        public int KitTemplateId { get; set; } // KitTemplateId

        [Column(@"Name", Order = 3, TypeName = "nvarchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 200)

        [Column(@"Identifier", Order = 4, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Identifier")]
        public string Identifier { get; set; } // Identifier (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent KitTemplate pointed by [KitTemplateAttribute].([KitTemplateId]) (FK_KitTemplateAttribute_KitTemplate)
        /// </summary>
        [ForeignKey("KitTemplateId")] public virtual KitTemplate KitTemplate { get; set; } // FK_KitTemplateAttribute_KitTemplate
    }

}
// </auto-generated>
