// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo.Entities
{

    // KitTemplateMeasureDefinition
    [Table("KitTemplateMeasureDefinition", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplateMeasureDefinition
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"KitTemplateMeasureDefinitionId", Order = 1, TypeName = "int")]
        [Index(@"PK_KitTemplateMeasureDefinition", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Kit template measure definition ID")]
        public int KitTemplateMeasureDefinitionId { get; set; } // KitTemplateMeasureDefinitionId (Primary key)

        [Column(@"KitTemplateId", Order = 2, TypeName = "int")]
        [Display(Name = "Kit template ID")]
        public int? KitTemplateId { get; set; } // KitTemplateId

        [Column(@"Name", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 80)

        [Column(@"Unit", Order = 4, TypeName = "nvarchar")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Unit")]
        public string Unit { get; set; } // Unit (length: 30)

        [Column(@"MeasureType", Order = 5, TypeName = "varchar")]
        [Required]
        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Measure type")]
        public string MeasureType { get; set; } // MeasureType (length: 5)

        [Column(@"Formula", Order = 6, TypeName = "nvarchar")]
        [MaxLength(512)]
        [StringLength(512)]
        [Display(Name = "Formula")]
        public string Formula { get; set; } // Formula (length: 512)

        [Column(@"FormatString", Order = 7, TypeName = "nvarchar")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Format string")]
        public string FormatString { get; set; } // FormatString (length: 30)

        [Column(@"UnitFormat", Order = 8, TypeName = "nvarchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Unit format")]
        public string UnitFormat { get; set; } // UnitFormat (length: 200)

        [Column(@"Form", Order = 9, TypeName = "nvarchar(max)")]
        [Display(Name = "Form")]
        public string Form { get; set; } // Form

        [Column(@"FOD_cID", Order = 10, TypeName = "uniqueidentifier")]
        [Display(Name = "Fod c ID")]
        public System.Guid? FodCId { get; set; } // FOD_cID

        // Foreign keys

        /// <summary>
        /// Parent FodFormDefinition pointed by [KitTemplateMeasureDefinition].([FodCId]) (FK_KitTemplateMeasureDefinition_FOD_FormDefinitions)
        /// </summary>
        [ForeignKey("FodCId")] public virtual FodFormDefinition FodFormDefinition { get; set; } // FK_KitTemplateMeasureDefinition_FOD_FormDefinitions
        /// <summary>
        /// Parent KitTemplate pointed by [KitTemplateMeasureDefinition].([KitTemplateId]) (FK_KitTemplateMeasureDefinition_KitTemplate)
        /// </summary>
        [ForeignKey("KitTemplateId")] public virtual KitTemplate KitTemplate { get; set; } // FK_KitTemplateMeasureDefinition_KitTemplate
    }

}
// </auto-generated>
