// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo.Entities
{

    // KitTemplate
    [Table("KitTemplate", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class KitTemplate
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"KitTemplateId", Order = 1, TypeName = "int")]
        [Index(@"PK_KitTemplate", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Kit template ID")]
        public int KitTemplateId { get; set; } // KitTemplateId (Primary key)

        [Column(@"Name", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 100)

        [Column(@"Abbr", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Abbr")]
        public string Abbr { get; set; } // Abbr (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child KitTemplateAttributes where [KitTemplateAttribute].[KitTemplateId] point to this entity (FK_KitTemplateAttribute_KitTemplate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<KitTemplateAttribute> KitTemplateAttributes { get; set; } // KitTemplateAttribute.FK_KitTemplateAttribute_KitTemplate
        /// <summary>
        /// Child KitTemplateMeasureDefinitions where [KitTemplateMeasureDefinition].[KitTemplateId] point to this entity (FK_KitTemplateMeasureDefinition_KitTemplate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<KitTemplateMeasureDefinition> KitTemplateMeasureDefinitions { get; set; } // KitTemplateMeasureDefinition.FK_KitTemplateMeasureDefinition_KitTemplate

        public KitTemplate()
        {
            KitTemplateAttributes = new System.Collections.Generic.List<KitTemplateAttribute>();
            KitTemplateMeasureDefinitions = new System.Collections.Generic.List<KitTemplateMeasureDefinition>();
        }
    }

}
// </auto-generated>
