// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo.Entities
{

    // LOE_LogExceptions
    [Table("LOE_LogExceptions", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class LoeLogException
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"LOE_iNoSeq", Order = 1, TypeName = "int")]
        [Index(@"PK_LOE_LogExceptions", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Loe i no seq")]
        public int LoeINoSeq { get; set; } // LOE_iNoSeq (Primary key)

        [Column(@"CLI_cID", Order = 2, TypeName = "uniqueidentifier")]
        [Display(Name = "Cli c ID")]
        public System.Guid? CliCId { get; set; } // CLI_cID

        [Column(@"LOE_dtCreated", Order = 3, TypeName = "datetime")]
        [Index(@"IX_LOE_dtCreated", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Loe dt created")]
        public System.DateTime LoeDtCreated { get; set; } // LOE_dtCreated

        [Column(@"LOE_cType", Order = 4, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Loe c type")]
        public string LoeCType { get; set; } // LOE_cType (length: 50)

        [Column(@"LOE_cMessage", Order = 5, TypeName = "varchar(max)")]
        [Required]
        [Display(Name = "Loe c message")]
        public string LoeCMessage { get; set; } // LOE_cMessage

        [Column(@"LOE_cNote", Order = 6, TypeName = "varchar(max)")]
        [Display(Name = "Loe c note")]
        public string LoeCNote { get; set; } // LOE_cNote

        [Column(@"LOE_dtLastModified", Order = 7, TypeName = "datetime")]
        [Display(Name = "Loe dt last modified")]
        public System.DateTime? LoeDtLastModified { get; set; } // LOE_dtLastModified

        [Column(@"LOE_bDeleted", Order = 8, TypeName = "bit")]
        [Index(@"IX_LOE_Deleted", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Loe b deleted")]
        public bool LoeBDeleted { get; set; } // LOE_bDeleted
    }

}
// </auto-generated>
