// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo.Entities
{

    // SER_Servers
    [Table("SER_Servers", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class SerServer
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SER_cID", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_SER_Servers", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Ser c ID")]
        public System.Guid SerCId { get; set; } // SER_cID (Primary key)

        [Column(@"SER_dtCreated", Order = 2, TypeName = "datetime")]
        [Required]
        [Display(Name = "Ser dt created")]
        public System.DateTime SerDtCreated { get; set; } // SER_dtCreated

        [Column(@"SER_dtLastModified", Order = 3, TypeName = "datetime")]
        [Required]
        [Display(Name = "Ser dt last modified")]
        public System.DateTime SerDtLastModified { get; set; } // SER_dtLastModified

        [Column(@"SER_dtDeleted", Order = 4, TypeName = "datetime")]
        [Display(Name = "Ser dt deleted")]
        public System.DateTime? SerDtDeleted { get; set; } // SER_dtDeleted

        [Column(@"SER_vcName", Order = 5, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Ser vc name")]
        public string SerVcName { get; set; } // SER_vcName (length: 50)

        [Column(@"SER_vcJobAgentTag", Order = 6, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Ser vc job agent tag")]
        public string SerVcJobAgentTag { get; set; } // SER_vcJobAgentTag (length: 50)

        [Column(@"SER_vcConnectionStringEntities", Order = 7, TypeName = "nvarchar(max)")]
        [Display(Name = "Ser vc connection string entities")]
        public string SerVcConnectionStringEntities { get; set; } // SER_vcConnectionStringEntities

        [Column(@"SER_vcConnectionString", Order = 8, TypeName = "nvarchar(max)")]
        [Display(Name = "Ser vc connection string")]
        public string SerVcConnectionString { get; set; } // SER_vcConnectionString

        [Column(@"SER_bEnabled", Order = 9, TypeName = "bit")]
        [Required]
        [Display(Name = "Ser b enabled")]
        public bool SerBEnabled { get; set; } // SER_bEnabled

        [Column(@"SER_bCreateClientAvailable", Order = 10, TypeName = "bit")]
        [Required]
        [Display(Name = "Ser b create client available")]
        public bool SerBCreateClientAvailable { get; set; } // SER_bCreateClientAvailable

        // Reverse navigation

        /// <summary>
        /// Child CliClients where [CLI_Clients].[SER_cID] point to this entity (FK_CLI_Clients_SER_Servers)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CliClient> CliClients { get; set; } // CLI_Clients.FK_CLI_Clients_SER_Servers

        public SerServer()
        {
            SerBCreateClientAvailable = true;
            CliClients = new System.Collections.Generic.List<CliClient>();
        }
    }

}
// </auto-generated>
