// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindDemo.Entities
{

    // UNO_UserNotices
    [Table("UNO_UserNotices", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class UnoUserNotice
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"UNO_cID", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_UNO_UserNotices", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Uno c ID")]
        public System.Guid UnoCId { get; set; } // UNO_cID (Primary key)

        [Column(@"UNO_dtCreated", Order = 2, TypeName = "datetime")]
        [Required]
        [Display(Name = "Uno dt created")]
        public System.DateTime UnoDtCreated { get; set; } // UNO_dtCreated

        [Column(@"UNO_dtLastModified", Order = 3, TypeName = "datetime")]
        [Required]
        [Display(Name = "Uno dt last modified")]
        public System.DateTime UnoDtLastModified { get; set; } // UNO_dtLastModified

        [Column(@"UNO_dtDeleted", Order = 4, TypeName = "datetime")]
        [Display(Name = "Uno dt deleted")]
        public System.DateTime? UnoDtDeleted { get; set; } // UNO_dtDeleted

        [Column(@"UNO_vcConfidentialityEN", Order = 5, TypeName = "nvarchar(max)")]
        [Display(Name = "Uno vc confidentiality en")]
        public string UnoVcConfidentialityEn { get; set; } // UNO_vcConfidentialityEN

        [Column(@"UNO_vcConfidentialityFR", Order = 6, TypeName = "nvarchar(max)")]
        [Display(Name = "Uno vc confidentiality fr")]
        public string UnoVcConfidentialityFr { get; set; } // UNO_vcConfidentialityFR

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"UNO_iVersion", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Uno i version")]
        public int UnoIVersion { get; set; } // UNO_iVersion

        [Column(@"UNO_vcConfidentialityES", Order = 8, TypeName = "nvarchar(max)")]
        [Display(Name = "Uno vc confidentiality es")]
        public string UnoVcConfidentialityEs { get; set; } // UNO_vcConfidentialityES

        // Reverse navigation

        /// <summary>
        /// Child UseUsers where [USE_Users].[UNO_cID] point to this entity (FK_USE_Users_UNO_UserNotices)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UseUser> UseUsers { get; set; } // USE_Users.FK_USE_Users_UNO_UserNotices

        public UnoUserNotice()
        {
            UseUsers = new System.Collections.Generic.List<UseUser>();
        }
    }

}
// </auto-generated>
