// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo.Configurations
{

    using NorthwindDemo.Entities;

    // FST_FormSyncTasks
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class FstFormSyncTaskConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FstFormSyncTask>
    {
        public FstFormSyncTaskConfiguration()
            : this("dbo")
        {
        }

        public FstFormSyncTaskConfiguration(string schema)
        {
            Property(x => x.FstCAction).IsOptional().IsUnicode(false);
            Property(x => x.CliCId).IsOptional();
            Property(x => x.FodCId).IsOptional();
            Property(x => x.FdvCId).IsOptional();
            Property(x => x.FdcIId).IsOptional();
            Property(x => x.FstCError).IsOptional().IsUnicode(false);

        }
    }

}
// </auto-generated>
