// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo.Configurations
{

    using NorthwindDemo.Entities;

    // IPS_IpServers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class IpsIpServerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<IpsIpServer>
    {
        public IpsIpServerConfiguration()
            : this("dbo")
        {
        }

        public IpsIpServerConfiguration(string schema)
        {
            Property(x => x.IpsCTag).IsOptional();
            Property(x => x.IpsCWebService).IsOptional();
            Property(x => x.IpsCSignalRService).IsOptional();
            Property(x => x.IpsCFtpService).IsOptional();
            Property(x => x.IpsCSqlIpAddress).IsOptional();
            Property(x => x.IpsCBasicSqlAuthentification).IsOptional();
            Property(x => x.IpsCConnectionString).IsOptional();
            Property(x => x.IpsCEntitiesConnectionString).IsOptional();
            Property(x => x.IpsCNewDatabaseSource).IsOptional();
        }
    }

}
// </auto-generated>
