// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace NorthwindDemo.Configurations
{

    using NorthwindDemo.Entities;

    // SER_Servers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class SerServerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SerServer>
    {
        public SerServerConfiguration()
            : this("dbo")
        {
        }

        public SerServerConfiguration(string schema)
        {
            Property(x => x.SerDtDeleted).IsOptional();
            Property(x => x.SerVcJobAgentTag).IsOptional();
            Property(x => x.SerVcConnectionStringEntities).IsOptional();
            Property(x => x.SerVcConnectionString).IsOptional();
        }
    }

}
// </auto-generated>
